name: Detect Self-hosted Runner Timeout
on:
  workflow_call:
    inputs:
      unique-id:
        required: true
        type: string
      is-self-hosted:
        required: true
        type: boolean

jobs:
  # In the unlikely event a self-hosted runner was selected and reserved but it
  # goes down before the workload starts, cancel the workflow run.
  runner-timeout:
    if: ${{ inputs.is-self-hosted }}
    name: Detect Runner Timeout
    runs-on: ubuntu-latest
    steps:
      - uses: delan/servo-ci@main
      - name: Cancel if workload job is still queued
        run: |
          ci runner timeout \
            --wait-time 120 \
            --unique-id '${{ inputs.unique-id }}' \
            --github-repository '${{ github.repository }}' \
            --github-run-id '${{ github.run_id }}' \
            --github-token '${{ secrets.GITHUB_TOKEN }}'
