name: Select Self-hosted Runner
on:
  workflow_call:
    inputs:
      github-hosted-runner-label:
        required: true
        type: string
      self-hosted-image-name:
        required: true
        type: string
      self-hosted-runner-scope:
        required: false
        type: string
        default: /orgs/${{ github.repository_owner }}/actions/runners
      force-github-hosted-runner:
        required: false
        type: boolean
        default: false
    outputs:
      unique-id:
        value: ${{ jobs.runner-select.outputs.unique-id }}
      selected-runner-label:
        value: ${{ jobs.runner-select.outputs.selected-runner-label }}
      is-self-hosted:
        value: ${{ jobs.runner-select.outputs.is-self-hosted }}

jobs:
  # Selects a self-hosted runner if available, or else a GitHub-hosted runner.
  # We generate a unique id for the workload, then ask our monitor API to
  # reserve a self-hosted runner for us.
  runner-select:
    name: Select Runner
    runs-on: ubuntu-latest
    outputs:
      unique-id: ${{ steps.select.outputs.unique_id }}
      selected-runner-label: ${{ steps.select.outputs.selected_runner_label }}
      is-self-hosted: ${{ steps.select.outputs.is_self_hosted }}
    steps:
      - uses: delan/servo-ci@main
      - name: Select and reserve best available runner
        id: select
        run: |
          ci runner select \
            --github-repository '${{ github.repository }}' \
            --github-run-id '${{ github.run_id }}' \
            --monitor-api-token '${{ secrets.SERVO_CI_MONITOR_API_TOKEN }}' \
            --github-hosted-runner-label '${{ inputs.github-hosted-runner-label }}' \
            --self-hosted-image-name '${{ inputs.self-hosted-image-name }}'
